/**
 * @file dynamic_resolve.h
 * @brief PEB-based dynamic API resolution engine for PhantomLDAP BOF suite.
 *
 * Provides a zero-import mechanism for resolving Windows API function
 * addresses at runtime by walking the Process Environment Block (PEB)
 * loader data and matching module/function names using a DJB2 hash.
 *
 * ## Motivation
 * Standard C imports create entries in the PE Import Address Table (IAT),
 * allowing EDR solutions to perform static analysis on the compiled object
 * and detect the presence of sensitive API calls (e.g., ldap_search_ext_s).
 *
 * By resolving all sensitive APIs dynamically at runtime, PhantomLDAP's
 * compiled `.o` files contain NO references to wldap32.dll or its exports
 * in their import tables, substantially reducing the static detection surface.
 *
 * ## Algorithm Overview
 * 1. Read TEB via GS segment register (x64) to obtain the PEB pointer.
 * 2. Walk PEB->Ldr->InMemoryOrderModuleList to enumerate loaded modules.
 * 3. Compute DJB2 hash of each module's BaseDllName and compare to target.
 * 4. On match, parse the module's PE export table (IMAGE_EXPORT_DIRECTORY).
 * 5. For each exported name, compute DJB2 hash and compare to target.
 * 6. Return the resolved function address (RVA -> VA conversion).
 *
 * ## Pre-computed Hash Table
 * All hash values were generated by scripts/gen_hashes.py using the same
 * DJB2 implementation present in dynamic_resolve.c.
 *
 * @author  PhantomLDAP Project
 * @version 1.0.0
 */

#ifndef PHANTOM_DYNAMIC_RESOLVE_H
#define PHANTOM_DYNAMIC_RESOLVE_H

#include "win_types.h"
#include "ldap_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 * Pre-computed DJB2 Hashes — Module Names (lowercase)
 *
 * Generated by: python3 scripts/gen_hashes.py
 * Algorithm: djb2 (hash * 33 + c, seed = 5381, case-insensitive)
 * ========================================================================= */

#define PHANTOM_HASH_WLDAP32                               0xCB9A778CUL    /**< djb2("wldap32.dll")    */
#define PHANTOM_HASH_KERNEL32                              0x7040EE75UL    /**< djb2("kernel32.dll")   */
#define PHANTOM_HASH_NTDLL                                 0x22D3B5EDUL    /**< djb2("ntdll.dll")      */
#define PHANTOM_HASH_NETAPI32                              0x60C3DB35UL    /**< djb2("netapi32.dll")   */

/* =========================================================================
 * Pre-computed DJB2 Hashes — wldap32.dll Exports (case-sensitive)
 * ========================================================================= */

#define PHANTOM_HASH_ldap_initW                            0x826FBB90UL
#define PHANTOM_HASH_ldap_set_option                       0x0AE24289UL
#define PHANTOM_HASH_ldap_get_option                       0xDA6374FDUL
#define PHANTOM_HASH_ldap_connect                          0x121C14AFUL
#define PHANTOM_HASH_ldap_bind_sW                          0xB71D50CBUL
#define PHANTOM_HASH_ldap_unbind                           0xEC611305UL
#define PHANTOM_HASH_ldap_search_ext_sW                    0x11EDAC34UL
#define PHANTOM_HASH_ldap_count_entries                    0xB1182BE7UL
#define PHANTOM_HASH_ldap_first_entry                      0x95FA451EUL
#define PHANTOM_HASH_ldap_next_entry                       0xD21F0995UL
#define PHANTOM_HASH_ldap_get_valuesW                      0x1E22036BUL
#define PHANTOM_HASH_ldap_get_values_lenW                  0x9DC97A09UL
#define PHANTOM_HASH_ldap_count_valuesW                    0xAED3F654UL
#define PHANTOM_HASH_ldap_count_values_len                 0x290C81BBUL
#define PHANTOM_HASH_ldap_value_freeW                      0x66748CFAUL
#define PHANTOM_HASH_ldap_value_free_len                   0x8F485EA1UL
#define PHANTOM_HASH_ldap_msgfree                          0x1CB43FAEUL
#define PHANTOM_HASH_ldap_get_dnW                          0x2F15C7CDUL
#define PHANTOM_HASH_ldap_memfreeW                         0x8B8BD6FDUL
#define PHANTOM_HASH_ldap_first_attributeW                 0x28C583D7UL
#define PHANTOM_HASH_ldap_next_attributeW                  0xE41AAAAEUL
#define PHANTOM_HASH_ber_free                              0x5C7DD0DFUL
#define PHANTOM_HASH_ldap_create_page_controlW             0x0C9424CCUL
#define PHANTOM_HASH_ldap_parse_page_controlW              0xEC8443D3UL
#define PHANTOM_HASH_ldap_parse_resultW                    0x9016E655UL
#define PHANTOM_HASH_ldap_controls_freeA                   0xA233BCFBUL
#define PHANTOM_HASH_ldap_err2stringW                      0x1D301AEEUL

/* =========================================================================
 * Pre-computed DJB2 Hashes — kernel32.dll Exports
 * ========================================================================= */

#define PHANTOM_HASH_HeapAlloc                             0x1FFD670EUL
#define PHANTOM_HASH_HeapFree                              0x374893C5UL
#define PHANTOM_HASH_HeapReAlloc                           0x1E31C125UL
#define PHANTOM_HASH_GetProcessHeap                        0xC6580D02UL
#define PHANTOM_HASH_LoadLibraryW                          0x5FBFF111UL
#define PHANTOM_HASH_GetProcAddress                        0xCF31BB1FUL
#define PHANTOM_HASH_WideCharToMultiByte                   0xE65D31CEUL
#define PHANTOM_HASH_MultiByteToWideChar                   0xE2FDDA8EUL
#define PHANTOM_HASH_lstrlenW                              0xD2C4AB20UL

/* =========================================================================
 * DJB2 Hash Function
 * ========================================================================= */

/**
 * @brief Compute a DJB2 hash of a null-terminated ASCII string.
 *
 * Implementation:
 *   hash = 5381
 *   for each byte c: hash = (hash << 5) + hash + c   [= hash * 33 + c]
 *
 * @param str               Input string (ASCII, null-terminated)
 * @param case_insensitive  If TRUE, converts uppercase to lowercase before hashing
 * @return                  32-bit DJB2 hash value
 */
DWORD phantom_hash_ascii(const char *str, BOOL case_insensitive);

/**
 * @brief Compute a DJB2 hash of a null-terminated wide (Unicode) string.
 *
 * Converts each WCHAR to its lower-byte ASCII equivalent before hashing.
 * This is intentionally lossy for names that contain only ASCII characters
 * (which all Windows module and function names do in practice).
 *
 * @param str               Input wide string (null-terminated)
 * @param case_insensitive  If TRUE, lowercases each character before hashing
 * @return                  32-bit DJB2 hash value
 */
DWORD phantom_hash_unicode(const WCHAR *str, BOOL case_insensitive);

/* =========================================================================
 * Module & Function Resolution
 * ========================================================================= */

/**
 * @brief Locate a loaded module's base address by its DJB2 hash.
 *
 * Walks PEB->Ldr->InMemoryOrderModuleList and computes the DJB2 hash
 * of each module's BaseDllName (case-insensitive Unicode-to-ASCII).
 *
 * @param module_hash   Pre-computed DJB2 hash of the module name (lowercase)
 * @return              Base address (DllBase) of the matching module,
 *                      or NULL if not found / module not loaded.
 */
PVOID phantom_get_module_base(DWORD module_hash);

/**
 * @brief Resolve a function's address by its DJB2 hash from a loaded module.
 *
 * Parses the module's PE export directory (IMAGE_EXPORT_DIRECTORY), iterates
 * over AddressOfNames, hashes each entry, and returns the resolved VA when
 * a match is found.
 *
 * @param module_base   Base address of the target module (from phantom_get_module_base)
 * @param func_hash     Pre-computed DJB2 hash of the export name (case-sensitive)
 * @return              Virtual address of the exported function,
 *                      or NULL if the export is not found.
 */
PVOID phantom_get_proc_addr(PVOID module_base, DWORD func_hash);

/**
 * @brief Combined one-shot module+function resolution.
 *
 * Equivalent to:
 *   phantom_get_proc_addr(phantom_get_module_base(mod_hash), func_hash)
 *
 * @param mod_hash      Module name hash
 * @param func_hash     Function name hash
 * @return              Resolved function VA or NULL
 */
PVOID phantom_resolve(DWORD mod_hash, DWORD func_hash);

/* =========================================================================
 * LDAP API Table Initialization
 * ========================================================================= */

/**
 * @brief Resolve all wldap32.dll function pointers into a PHANTOM_LDAP_API table.
 *
 * This function:
 * 1. Locates wldap32.dll in the PEB module list (or loads it if absent).
 * 2. Resolves each function in PHANTOM_LDAP_API using the export hash table.
 * 3. Verifies all pointers are non-NULL before returning.
 *
 * @param api   Pointer to a zeroed PHANTOM_LDAP_API structure to populate.
 * @return      TRUE if all functions were successfully resolved,
 *              FALSE if any resolution failed (partial table — do not use).
 *
 * @note wldap32.dll is typically already loaded in any domain-joined process
 *       that has performed Kerberos authentication. If it is not loaded, this
 *       function will attempt to load it using a dynamically-resolved
 *       LoadLibraryW call, which itself is resolved via PEB walking.
 */
BOOL phantom_resolve_ldap_api(PPHANTOM_LDAP_API api);

/* =========================================================================
 * Kernel32 Heap API (dynamically resolved for OpSec)
 * ========================================================================= */

/**
 * @brief Phantom-resolved wrapper for HeapAlloc.
 *
 * Uses a lazily-cached HeapAlloc function pointer resolved via PEB walking
 * to avoid a static kernel32 import for memory allocation.
 *
 * @param size      Number of bytes to allocate
 * @param zeroed    If TRUE, zero-initialize the allocation (HEAP_ZERO_MEMORY)
 * @return          Pointer to allocated memory, or NULL on failure
 */
PVOID phantom_heap_alloc(SIZE_T size, BOOL zeroed);

/**
 * @brief Phantom-resolved wrapper for HeapFree.
 *
 * @param ptr       Pointer previously returned by phantom_heap_alloc
 */
void phantom_heap_free(PVOID ptr);

/**
 * @brief Phantom-resolved wrapper for HeapReAlloc.
 *
 * @param ptr       Existing allocation
 * @param new_size  New allocation size in bytes
 * @return          Reallocated pointer, or NULL on failure
 */
PVOID phantom_heap_realloc(PVOID ptr, SIZE_T new_size);

/* =========================================================================
 * Convenience Macros
 * ========================================================================= */

/**
 * @brief Safely free and null-out a heap allocation.
 */
#define PHANTOM_FREE(ptr) do { if (ptr) { phantom_heap_free(ptr); (ptr) = NULL; } } while(0)

/**
 * @brief Allocate zeroed memory and abort (goto cleanup) on failure.
 * @param ptr   Variable to assign
 * @param sz    Allocation size
 * @param lbl   Cleanup label to jump to on failure
 */
#define PHANTOM_ALLOC_OR_CLEANUP(ptr, sz, lbl) \
    do { \
        (ptr) = phantom_heap_alloc((sz), TRUE); \
        if (!(ptr)) { \
            BeaconPrintf(CALLBACK_ERROR, "[!] PhantomLDAP: HeapAlloc failed (%zu bytes)\n", (SIZE_T)(sz)); \
            goto lbl; \
        } \
    } while(0)

/**
 * @brief Check LDAP return code and log + jump to cleanup on failure.
 */
#define PHANTOM_LDAP_CHECK(rc, msg, lbl) \
    do { \
        if ((rc) != LDAP_SUCCESS) { \
            BeaconPrintf(CALLBACK_ERROR, "[!] PhantomLDAP: %s failed (LDAP error 0x%02lX)\n", (msg), (ULONG)(rc)); \
            goto lbl; \
        } \
    } while(0)

#ifdef __cplusplus
}
#endif

#endif /* PHANTOM_DYNAMIC_RESOLVE_H */
